### ISSUE TITLE
Homepage typo error

### ISSUE THREAD

**Issue by tomsihap** [thephpleague/thephpleague.github.io#100]
**Location** https://thephpleague.com/ french homepage

**Related file** https://github.com/thephpleague/thephpleague.github.io/blob/master/_data/fr.yml

```md
   paragraph_3: [...] vielle [...] 
```

Must be changed to:
```md
    paragraph_3: [...] vieille [...] 
```

**Comment by colinodell** [comment]
This has been fixed! Thanks for letting us know :)
