### ISSUE TITLE
no secure way to load css/js

### ISSUE THREAD

**Issue by Symphlion** [thephpleague/thephpleague.github.io#76]
Don't know where to let you guys know so i'll do it here, but loading in from http while on https doesn't work. On the root domain it's OK because it's a relative path, on the subdomains ( i.e. https://container.thephpleague.com ) it's not working. 

Hope you'll be able to fix it.

**Comment by reinink** [comment]
Yeah, our site doesn't currently support HTTPS. It is hosted with GitHub Pages, which as far as I know, does not support this. Just hit up the non-HTTP version of the site instead. Ie: http://container.thephpleague.com/

**Comment by Symphlion** [comment]
Fair enough, i'll add an exception to https everywhere!

**Comment by frankdejonge** [comment]
I got this.

**Comment by frankdejonge** [comment]
@Symphlion @reinink check-it: https://flysystem.thephpleague.com/

**Comment by reinink** [comment]
Right, because we're hosting with Cloudflare. Nice!

**Comment by Symphlion** [comment]
:+1:
