### ISSUE TITLE
Definition of quality, remove League?

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/thephpleague.github.io#80]
So this is the current definition:

> 1. Use League as the PSR-4 autoloader namespace. Shove code in a src folder.
> 2. Adhere to PSR-2 as the coding style guide.
> 3. List on Packagist with league as the vendor namespace.
> 4. Write unit tests. Aim for at least 80% coverage in version 1.
> 5. DocBlock all the things.
> 6. Use Semantic Versioning to manage version numbers.
> 7. Keep a Changelog.
> 8. Use Travis-CI to automatically check coding standards and run tests.
> 9. Have an extensive README.
> 10. Exclude non-essential files in .gitattributes.

Are 1 and 3 really quality traits? 1 could just be 'Use a PSR-4 autoloader namespace. Shove code in a src folder.` and 3: `List the package on Packagist` (or be removed).

This could people give the false idea that it needs to be in this namespace, before submitting a package proposal (although the recruitment statement is dropped, people still submit)

**Comment by frankdejonge** [comment]
👍  I agree

**Comment by philsturgeon** [comment]
👍 on changing this. As a brief history note, I think it used to say:

> Use a namespace (we use League) as the PSR-4 autoloader namespace. Shove code in a src folder.

and 

> List on Packagist with a vendor namespace (we use `league/`).

or something like that. 

It's definitely not trying to say

> If it doesn't have league in the title then you're a piece of shit

but I can see how it could end up looking like that 😨

**Comment by GrahamCampbell** [comment]
> Shove code in a src folder.

That bit needs to stay I think?

**Comment by philsturgeon** [comment]
I think I'm gonna close this, LMK if anyone else has concerns. We're gonna have a curated list of quality third party packages soon and that'll make it clear we aren't only considering projects good if they start with `League/`. I get whats being said, but trying to get more wordy with it at this point is unnecessary. 

Again, hopefully it should be clear that we aren't saying "If it doesn't have league in the title then you're a piece of shit" :)
