### ISSUE TITLE
Add Curated Packages

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/thephpleague.github.io#82]
People have for a long time suggested that The League should be something different from what it is, and since Day 1 people showed interest in it becoming a Curated Package list, where we point to awesome stuff that doesn't happen to have the `League/` namespace on it.

I like this idea a lot. We have have a curated package list which has links to other cool stuff, that follows a bunch of our metrics of quality, or enough of http://phppackagechecklist.com/.

**Comment by Webysther** [comment]
I had the same problem, look: i have this project i start but i need to create a docker, stay on my namespace?
Other question are about location of project, need stay inside thephpleague organization?

**Comment by frankdejonge** [comment]
There are a number of "awesome PHP" lists out there and downloads/popularity are filters in Packagist now. Closing this as "not needed anymore".
