### ISSUE TITLE
Fractal ArraySerializer docs are incorrect

### ISSUE THREAD

**Issue by brandonkelly** [thephpleague/thephpleague.github.io#84]
The example given for how Collections with metadata are serialized using [ArraySerializer](http://fractal.thephpleague.com/serializers/#arrayserializer) is incorrect, and it’s not even valid JSON:

```js
// Collection with Meta
[
    [
        'foo' => 'bar'
    ]
    'meta' => [
        ...
    ]
];
```

In reality it will be:

```js
// Collection with Meta
[
    'data' => [
        {
            'foo' => 'bar'
        }
    ],
    'meta' => [
        ...
    ]
];
```

Other parts of the ArraySerializer docs give it a bad wrap as well, for no good reason, as the collections do in fact get tucked inside a `data` attribute.

As far as I can tell, there’s only two differences between ArraySerializer and DataArraySerializer:

1. ArraySerializer serializes the resource at the top level rather than under a `data` key
2. ArraySerializer respects the `resourceKey` it was configured with; DataArraySerializer forces `'data'` (which seems like a bug, but will file a separate issue on the Fractal repo for that)

**Comment by frankdejonge** [comment]
@brandonkelly Hi, could you submit this issue to the fractal repository, that way the maintainers are notified and it can be picked up. Even better would be a PR on the gh-pages branch of that repo to change the docs.

**Comment by brandonkelly** [comment]
- [x] https://github.com/thephpleague/fractal/issues/388
