### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by mstnorris** [thephpleague/thephpleague.github.io#85]
On http://pipeline.thephpleague.com/usage/ under the heading **Exception handling**:

> This package is completely transparent when dealing with exception. In no case will this package catch an exception or silence an error. Exception should be dealt with on a per-case ~basic~ **basis**. Either inside a stage or at time when the pipeline processes a payload.

**Comment by colinodell** [comment]
Good catch!  Would you mind reporting it to the [pipline repository](https://github.com/thephpleague/pipeline)?  That way the project maintainers will be notified and can make the fix.

Or for bonus points, you could submit a PR for their `gh-pages` branch (which contains the documentation website) to make that change: https://github.com/thephpleague/pipeline/tree/gh-pages :)

**Comment by mstnorris** [comment]
PR Done.

Thanks, I couldn't find the docs.

Kind regards,

Michael


—


Michael Norris

+44 (0) 7446 990 061
hello@michaelnorris.co.uk
https://michaelnorris.co.uk

On 22 May 2017 at 20:51:32, colinodell (notifications@github.com) wrote:

Good catch! Would you mind reporting it to the pipline repository? That way the project maintainers will be notified and can make the fix.

Or for bonus points, you could submit a PR for their gh-pages branch (which contains the documentation website) to make that change: https://github.com/thephpleague/pipeline/tree/gh-pages :)

**Comment by colinodell** [comment]
Thank you!
