### ISSUE TITLE
How ask permission to put some project inside organization?

### ISSUE THREAD

**Issue by Webysther** [thephpleague/thephpleague.github.io#88]
I [started a project](https://github.com/Webysther/mirror) using the guidelines, how put inside the organization?
I need create a docker too, thephpleague have a hub.docker.com organization?

**Comment by frankdejonge** [comment]
Hi, we're not recruiting new member projects any more. Please publish your project under your own namespace.

**Comment by Webysther** [comment]
Interesting, thanks.
