### ISSUE TITLE
Website down ("DNS_PROBE_FINISHED_NXDOMAIN")

### ISSUE THREAD

**Issue by tyrann0us** [thephpleague/thephpleague.github.io#92]
@frankdejonge, @ragboyjr, https://thephpleague.com/ is currently unavailable:

![thephpleague com](https://user-images.githubusercontent.com/8144115/42800534-a73890de-899c-11e8-8c8c-e3dbec752c54.jpeg)

This also affects http://theme.thephpleague.com/ and thus http://platesphp.com/ looks broken.

**Comment by frankdejonge** [comment]
It should be ok now, we were transferring the domain. Which has just taken effect. The nameservers have been adjusted to reflect the old situation again and should be available shortly.

**Comment by tyrann0us** [comment]
Can confirm the website is on. That was fast. :)
