### ISSUE TITLE
Hamburger Menu Broken: https://route.thephpleague.com/

### ISSUE THREAD

**Issue by rprattvtg** [thephpleague/thephpleague.github.io#97]
Click hamburger menu on upper right. Nothing happens. Shucks! Wanted to read docs! (Yeah, i can get them in the repo here, but not as pretty.)

Anyway, just to let you know :)

**Comment by rprattvtg** [comment]
Oh, both Firefox and Chrome on Windows and Android.

**Comment by frankdejonge** [comment]
This is fixed in https://github.com/thephpleague/route/pull/233

**Comment by frankdejonge** [comment]
Thanks for reporting the issue! 👍
