### ISSUE TITLE
Enhance package submission section in Wiki

### ISSUE THREAD

**Issue by peter279k** [thephpleague/thephpleague.github.io#98]
According to the package submission section in Wiki, it looks like the team suggests developers submit package proposals via Google group.

However, this org Google group has already been closed due to the lots of spam messages.

I think it should enhance this section and have the new approach/progress of submitting package :).

**Comment by zquintana** [comment]
I'd appreciate this also. In fact it would be nice if the project home page had a link to the doc that @peter279k is describing. I spent several hours yesterday looking for that doc.

**Comment by frankdejonge** [comment]
We are currently not open to submissions any more, so I've removed the page.
